### ISSUE TITLE
LizardFS Roadmap plan

### ISSUE THREAD

**Issue by blink69** [lizardfs/lizardfs#389]
Hi, 

on https://github.com/lizardfs/lizardfs/wiki/Roadmap we put our latest plan for next releases. You are welcome to comment :)

Best

**Comment by Zorlin** [comment]
Hi @blink69 - excellent transparency. Glad to see this sort of thing :)

* Any plans for "official" HA/failover (lizardfs-ucarp)?
* Any plans for storage tiering (SSDs etc)?

**Comment by onlyjob** [comment]
We need more fixes on roadmap. Or better in point releases. So far LizardFS team was not publishing point releases (e.g. 3.9.x) and while major release like 3.9.4 is affected by very serious bugs (for a long time) the only feasible way to use LizardFS is through official Debian packages where I cherry pick fixes. (Do not confuse official Debian packages from Debian repositories with _vendor_ packages. They are very different.).
Please follow [Software versioning](https://en.wikipedia.org/wiki/Software_versioning) practice. New major release should have version 3.9.0, not 3.9.8. Conclusion: use proper versioning and publish point releases often, as soon as serious fix is committed.

We all are waiting for Raft-based HA solution. Please do not withhold it for your commercial customers.

I'm disappointed that some simple but effective features are not on the roadmap. Notably #370 (sparse chunks) that is easy to implement with a big gain for space efficiency performance of small files.

At this time bug fixes are more and more important. I'd like to see bug squashing to be prioritised over implementation of new major features like jerasure coding. I'm looking forward to see #349 completely fixed as well as bugs like #343 and #338 (which is a known issue that can cause loss of data).

Also please include bug numbers to roadmap.

**Comment by 4Dolio** [comment]
Thank you for the roadmap.  I appreciate @onlyjob focus on 3.x bug squashing pressure bug I find myself wishing that 2.x were still receiving attention as it still feels like that is still the only stable branch.  Perhaps @blink69 and others would appreciate my corosync work If I felt it might be pulled into the 2.6.0-wip.  If that were a possibility I might take a stab at some carp solutions which should be trivial in comparison to corosync+pacemaker insanity.

I'm still perplexed with my recent experience in migrating from moosefs to lizardfs which resulted a substantial performance loss.  Granted the performance had been suffering with the growth of my dataset under moosefs.  Perhaps it is unrealistic to expect my ~125 million object ~50GiB Metadata ~200TiB disk cluster to perform well with either solution.  The LizardFS Shadow mechanic literally failed in my environment until I was able to lower the persistent load.  Was I simply expecting to much from a singular metadata namespace?

I likely should have taken the steps I recently have in fragmenting my data into smaller discrete LizardFS datasets.  Doing so would have in all likelihood also improved the old MooseFS performance.  I'm hoping that perhaps something can be done to address the shortcomings that I have encountered so to natively be able to more transparently address large growth of metadata while being able to maintain the good performance that smaller more discrete clusters appear to be able to deliver.

I am very thankful that LizardFS is so amenable to perhaps novel implementations such as what I am being forced to do by running multiple clusters on the same hardware on which I used to run just a single large namespace (which in retrospect was not scaling the way I had hoped).  I am really hoping to someday be able to re-unify all of my data back into a single LizardFS namespace/metadata set.  But we need some new features which I'm not really seeing much attention given being given to.

Another perhaps related shortcoming is the poor handling of sparse files.  It would be outstanding if somehow LizardFS could store sparse folder( structures) in mini-meta sets as a single 64GB chunk which could be dynamically loaded and unloaded from RAM in an effective and effective and tunable manor.

One final aspect of this scale problem demands that LizardFS address multi-thread-ability across multiple cores and among multiple masters.

> master: possibility to store names on disk (reduce memory usage)

This is the only hint I see of something that might lend itself to solving the above problems.  Could someone elaborate on this "store names on disk" feature?  I'm wondering if maybe this idea could be generalized into a sort of metadata-nesting mechanic which could perhaps be leveraged to address everything I have just mentioned?

I'm sticking with LizardFS for the foreseeable future and hoping that it can grow to support ever more complex goal, label, topology, and replication schemas so to be able to address ever larger, more rich,  and higher performance storage demands.

**Comment by gutleib** [comment]
@4Dolio  could you point me to squashing pressure bug?
We're thinking about using LizardFS, and I'm bit worried if it's a serious one.
Also, why do you consider 3.x unstable?

**Comment by onlyjob** [comment]
> Also, why do you consider 3.x unstable?

I'm curious about that as well. Remaining issues were addressed and fully updated LizardFS v3 packages are in official Debian repositories (including _jessie-backports_) with all backported patches. My 60 TiB 3.9.4+fixes cluster had no issues lately being very stable.
I do not miss 2.6.0 and I'm already enjoying new features. ;)

**Comment by onlyjob** [comment]
I mean I've tested 3.x most extensively and finally I feel reasonably confident about it...

**Comment by 4Dolio** [comment]
> could you point me to squashing pressure bug?

See @onlyjob reply prior to mine, all over fixing bugs...

I just haven't had much time for testing 3.x, I just read of early 3.x bugs.  I'm forced to keep running some moosefs 1.x clients which i fear may not play nice.  I also have some old FREEBSD 9.3 chunkservers which were difficult to compile 2.6 on and haven't even attempted 3.x on yet.  Perhaps I'll move from compiled 3.x to jessie-backports .deb sources in my test cluster soon and change my mind if old clients still behave.

**Comment by mbq** [comment]
About HA, maybe you can just relay to a separate distributed lock system? [Consul](https://www.consul.io/) with its [sessions API](https://www.consul.io/docs/internals/sessions.html) seem to be a good candidate. Also its DNS interface allows easy propagation of the current master IP to the chunkservers.

**Comment by Zorlin** [comment]
Would LizardFS consider implementing Semantic Versioning (http://semver.org/)? I think that would clear up a lot of confusion.

**Comment by onlyjob** [comment]
Here are few more links with information about versioning:

 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions)
 * https://en.wikipedia.org/wiki/Software_versioning

I don't care about Ubuntu (to say the least). Anyway they leech everything from Debian so you can already see LizardFS packages from Debian in Ubuntu: https://launchpad.net/ubuntu/+source/lizardfs

I strongly recommend to avoid inferior Ubuntu and use Debian instead.

**Comment by richard-scott** [comment]
Would it be possible to enhance the documentation on 'bit rot' and what LizardFS does to help combat that problem. I know about the HDD_TEST_FREQ option but what I can't seem to tell is what exactly what happenes every 10 seconds... 

1. does new sequential full scan start (if not running) on the server checking every chunk one after the other? 
2. Is a random chunk checked every 10 seconds? 
3. Is scanning multi-threaded and if so, can we set the number of threads to speed things up?

**Comment by matkor** [comment]
No plans of internal HA? :(  
So new master is elected from shadows in case of failure.
And mount master/shadow can be provided by multiplie ip# like mfsmaster=x.x.x.a,x.x.x.b ?

**Comment by onlyjob** [comment]
I think #366 (data compression) is worth including to Roadmap. It should be straightforward and easy enough to implement.

**Comment by blink69** [comment]
@matkor we will release our uraft HA package probably in 3.12.0 release

**Comment by guestisp** [comment]
Any ETA for HA ? Is 3.12.0 still correct as release ?

Will this native or a manual configuration is still needed ? In other words, by adding 3 masters (1 master, 2 shadows) will Lizard be able to provide HA and failover automatically without using external scripts ?

**Comment by guestisp** [comment]
> on https://github.com/lizardfs/lizardfs/wiki/Roadmap we put our latest plan for next releases. You are welcome to comment :)

Is this stil updated ? Seems a little be outdated, some feature being worked (like NFS Ganesha) are not wrote there.
